/*
 * generated by Xtext 2.22.0
 */
package fr.gwendal_jouneaux.rob_lang.serializer;

import com.google.inject.Inject;
import fr.gwendal_jouneaux.rob_lang.services.RobLANGGrammarAccess;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public class RobLANGSyntacticSequencer extends AbstractSyntacticSequencer {

	protected RobLANGGrammarAccess grammarAccess;
	protected AbstractElementAlias match_Primary_LeftParenthesisKeyword_0_0_a;
	protected AbstractElementAlias match_Primary_LeftParenthesisKeyword_0_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (RobLANGGrammarAccess) access;
		match_Primary_LeftParenthesisKeyword_0_0_a = new TokenAlias(true, true, grammarAccess.getPrimaryAccess().getLeftParenthesisKeyword_0_0());
		match_Primary_LeftParenthesisKeyword_0_0_p = new TokenAlias(true, false, grammarAccess.getPrimaryAccess().getLeftParenthesisKeyword_0_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_Primary_LeftParenthesisKeyword_0_0_a.equals(syntax))
				emit_Primary_LeftParenthesisKeyword_0_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_Primary_LeftParenthesisKeyword_0_0_p.equals(syntax))
				emit_Primary_LeftParenthesisKeyword_0_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '!' expression=Primary
	 *     (rule start) (ambiguity) 'Array.get(' array=Expression
	 *     (rule start) (ambiguity) 'Array.length(' array=Expression
	 *     (rule start) (ambiguity) 'Array.new(' dimension=INT
	 *     (rule start) (ambiguity) 'Math.abs(' expression=Expression
	 *     (rule start) (ambiguity) 'Math.cos(' expression=Expression
	 *     (rule start) (ambiguity) 'Math.modulo(' lhs=Expression
	 *     (rule start) (ambiguity) 'Math.pow(' value=Expression
	 *     (rule start) (ambiguity) 'Math.sin(' expression=Expression
	 *     (rule start) (ambiguity) 'Math.sqrt(' expression=Expression
	 *     (rule start) (ambiguity) 'getBatteryLevel' '(' ')' (rule start)
	 *     (rule start) (ambiguity) 'getCompassAngle' '(' ')' (rule start)
	 *     (rule start) (ambiguity) 'getDistance' '(' sensorIndex=INT
	 *     (rule start) (ambiguity) 'getPosition' '(' ')' (rule start)
	 *     (rule start) (ambiguity) 'getTimestamp' '(' ')' (rule start)
	 *     (rule start) (ambiguity) function=[FunDefinition|ID]
	 *     (rule start) (ambiguity) value='false'
	 *     (rule start) (ambiguity) value='true'
	 *     (rule start) (ambiguity) value=DOUBLE
	 *     (rule start) (ambiguity) value=INT
	 *     (rule start) (ambiguity) value=STRING
	 *     (rule start) (ambiguity) variable=[Symbol|ID]
	 *     (rule start) (ambiguity) {And.left=}
	 *     (rule start) (ambiguity) {Divide.left=}
	 *     (rule start) (ambiguity) {Equality.left=}
	 *     (rule start) (ambiguity) {Greater.left=}
	 *     (rule start) (ambiguity) {GreaterEq.left=}
	 *     (rule start) (ambiguity) {Inequality.left=}
	 *     (rule start) (ambiguity) {Less.left=}
	 *     (rule start) (ambiguity) {LessEq.left=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Multiply.left=}
	 *     (rule start) (ambiguity) {Or.left=}
	 *     (rule start) (ambiguity) {Plus.left=}
	 */
	protected void emit_Primary_LeftParenthesisKeyword_0_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) {And.left=}
	 *     (rule start) (ambiguity) {Divide.left=}
	 *     (rule start) (ambiguity) {Equality.left=}
	 *     (rule start) (ambiguity) {Greater.left=}
	 *     (rule start) (ambiguity) {GreaterEq.left=}
	 *     (rule start) (ambiguity) {Inequality.left=}
	 *     (rule start) (ambiguity) {Less.left=}
	 *     (rule start) (ambiguity) {LessEq.left=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Multiply.left=}
	 *     (rule start) (ambiguity) {Or.left=}
	 *     (rule start) (ambiguity) {Plus.left=}
	 */
	protected void emit_Primary_LeftParenthesisKeyword_0_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
