/*
 * generated by Xtext 2.22.0
 */
package fr.gwendal_jouneaux.rob_lang.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RobLANGAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/gwendal_jouneaux/rob_lang/parser/antlr/internal/InternalRobLANG.tokens");
	}
}
