/*
 * generated by Xtext 2.22.0
 */
package fr.gwendal_jouneaux.rob_lang;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class RobLANGRuntimeModule extends AbstractRobLANGRuntimeModule {
}
