/**
 * generated by Xtext 2.22.0
 */
package fr.gwendal_jouneaux.rob_lang.robLANG;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fun Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.gwendal_jouneaux.rob_lang.robLANG.FunCall#getFunction <em>Function</em>}</li>
 *   <li>{@link fr.gwendal_jouneaux.rob_lang.robLANG.FunCall#getParams <em>Params</em>}</li>
 * </ul>
 *
 * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getFunCall()
 * @model
 * @generated
 */
public interface FunCall extends Expression
{
  /**
   * Returns the value of the '<em><b>Function</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Function</em>' reference.
   * @see #setFunction(FunDefinition)
   * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getFunCall_Function()
   * @model
   * @generated
   */
  FunDefinition getFunction();

  /**
   * Sets the value of the '{@link fr.gwendal_jouneaux.rob_lang.robLANG.FunCall#getFunction <em>Function</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Function</em>' reference.
   * @see #getFunction()
   * @generated
   */
  void setFunction(FunDefinition value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link fr.gwendal_jouneaux.rob_lang.robLANG.FunParam}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getFunCall_Params()
   * @model containment="true"
   * @generated
   */
  EList<FunParam> getParams();

} // FunCall
