/**
 * generated by Xtext 2.22.0
 */
package fr.gwendal_jouneaux.rob_lang.robLANG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Math Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getMathExpression()
 * @model
 * @generated
 */
public interface MathExpression extends Expression
{
} // MathExpression
