/**
 * generated by Xtext 2.22.0
 */
package fr.gwendal_jouneaux.rob_lang.robLANG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getStatement()
 * @model
 * @generated
 */
public interface Statement extends EObject
{
} // Statement
