/**
 * generated by Xtext 2.22.0
 */
package fr.gwendal_jouneaux.rob_lang.robLANG;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.gwendal_jouneaux.rob_lang.robLANG.Type#getType <em>Type</em>}</li>
 *   <li>{@link fr.gwendal_jouneaux.rob_lang.robLANG.Type#getDimension <em>Dimension</em>}</li>
 * </ul>
 *
 * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getType()
 * @model
 * @generated
 */
public interface Type extends EObject
{
  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * The literals are from the enumeration {@link fr.gwendal_jouneaux.rob_lang.robLANG.BasicType}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see fr.gwendal_jouneaux.rob_lang.robLANG.BasicType
   * @see #setType(BasicType)
   * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getType_Type()
   * @model
   * @generated
   */
  BasicType getType();

  /**
   * Sets the value of the '{@link fr.gwendal_jouneaux.rob_lang.robLANG.Type#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see fr.gwendal_jouneaux.rob_lang.robLANG.BasicType
   * @see #getType()
   * @generated
   */
  void setType(BasicType value);

  /**
   * Returns the value of the '<em><b>Dimension</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dimension</em>' attribute.
   * @see #setDimension(int)
   * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getType_Dimension()
   * @model
   * @generated
   */
  int getDimension();

  /**
   * Sets the value of the '{@link fr.gwendal_jouneaux.rob_lang.robLANG.Type#getDimension <em>Dimension</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dimension</em>' attribute.
   * @see #getDimension()
   * @generated
   */
  void setDimension(int value);

} // Type
