/*
 * generated by Xtext 2.22.0
 */
package fr.gwendal_jouneaux.rob_lang.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRobLANGScopeProvider extends DelegatingScopeProvider {
}
