/**
 * generated by Xtext 2.22.0
 */
package fr.gwendal_jouneaux.rob_lang.robLANG;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Array New</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.gwendal_jouneaux.rob_lang.robLANG.ArrayNew#getDimension <em>Dimension</em>}</li>
 * </ul>
 *
 * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getArrayNew()
 * @model
 * @generated
 */
public interface ArrayNew extends ArrayExpression
{
  /**
   * Returns the value of the '<em><b>Dimension</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dimension</em>' attribute.
   * @see #setDimension(int)
   * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getArrayNew_Dimension()
   * @model
   * @generated
   */
  int getDimension();

  /**
   * Sets the value of the '{@link fr.gwendal_jouneaux.rob_lang.robLANG.ArrayNew#getDimension <em>Dimension</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dimension</em>' attribute.
   * @see #getDimension()
   * @generated
   */
  void setDimension(int value);

} // ArrayNew
