/**
 * generated by Xtext 2.22.0
 */
package fr.gwendal_jouneaux.rob_lang.robLANG;

import fr.gjouneau.savm.framework.lang.semantics.AdaptableNode;
import fr.gwendal_jouneaux.rob_lang.interpreter.interfaces.MotorAdaptationInterface;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Move</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.gwendal_jouneaux.rob_lang.robLANG.Move#getDistance <em>Distance</em>}</li>
 * </ul>
 *
 * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getMove()
 * @model
 * @generated
 */
public interface Move extends Effector, AdaptableNode<MotorAdaptationInterface>
{
  /**
   * Returns the value of the '<em><b>Distance</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Distance</em>' containment reference.
   * @see #setDistance(Expression)
   * @see fr.gwendal_jouneaux.rob_lang.robLANG.RobLANGPackage#getMove_Distance()
   * @model containment="true"
   * @generated
   */
  Expression getDistance();

  /**
   * Sets the value of the '{@link fr.gwendal_jouneaux.rob_lang.robLANG.Move#getDistance <em>Distance</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Distance</em>' containment reference.
   * @see #getDistance()
   * @generated
   */
  void setDistance(Expression value);

} // Move
