/**
 * generated by Xtext 2.10.0
 */
package org.tetrabox.minijava.xtext.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;
import org.eclipse.xtext.ui.editor.outline.impl.DocumentRootNode;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#outline
 */
@SuppressWarnings("all")
public class MiniJavaOutlineTreeProvider extends DefaultOutlineTreeProvider {
  public boolean _isLeaf(final /* Method */Object m) {
    return true;
  }
  
  public void _createChildren(final DocumentRootNode outlineNode, final /* Program */Object model) {
    throw new Error("Unresolved compilation problems:"
      + "\nThere is no context to infer the closure\'s argument types from. Consider typing the arguments or put the closures into a typed context."
      + "\nclasses cannot be resolved"
      + "\nforEach cannot be resolved");
  }
}
