/**
 * generated by Xtext 2.10.0
 */
package org.tetrabox.minijava.xtext.ui.labeling;

import com.google.inject.Inject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.jface.viewers.StyledString;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.eclipse.xtext.xbase.lib.Extension;
import org.tetrabox.minijava.xtext.MiniJavaModelUtil;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class MiniJavaLabelProvider extends DefaultEObjectLabelProvider {
  @Inject
  public MiniJavaLabelProvider(final AdapterFactoryLabelProvider delegate) {
    super(delegate);
  }
  
  @Inject
  @Extension
  private MiniJavaModelUtil _miniJavaModelUtil;
  
  public StyledString text(final /* Member */Object m) {
    throw new Error("Unresolved compilation problems:"
      + "\nmemberAsString cannot be resolved"
      + "\ntypeRef cannot be resolved"
      + "\nname cannot be resolved");
  }
  
  public String image(final /* Method */Object m) {
    return "methpub_obj.gif";
  }
  
  public String image(final /* Field */Object f) {
    return "field_public_obj.gif";
  }
  
  public String image(final Class c) {
    return "_class_obj.gif";
  }
}
